idf_component_register(
    SRCS
        "app_main.cc"
        "camera_provider.cc"
        "identifier_detector.cc"
        "skippool_presence_binary_model_data.cc"
        "uart_comm.c"
    INCLUDE_DIRS
        "."
        "../../shared"
    REQUIRES
        esp_driver_gpio
        esp_driver_ledc
        esp_driver_uart
        esp-tflite-micro
        esp32-camera
        esp_timer
        nvs_flash
        driver
)
